---
name: Checks

on: [push]

jobs:
  test-link:
    name: Test and Lint
    run-on: Ubuntu 20.04.6
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: {{ secrets.DOCKER_FLIPDRUID }}
          password: {{ secrets.DOCKER_FLIPDRUID_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run:  docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"